"""empty message

Revision ID: 751965995f37
Revises: 3670e6ead9a9
Create Date: 2018-10-27 03:43:42.361906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751965995f37'
down_revision = '3670e6ead9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter_id')
    # ### end Alembic commands ###
