"""empty message

Revision ID: 9b38904c8900
Revises: 751965995f37
Create Date: 2018-10-28 07:20:59.716535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b38904c8900'
down_revision = '751965995f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccid', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.String(length=30), nullable=False),
    sa.Column('lng', sa.String(length=30), nullable=False),
    sa.Column('alt', sa.String(length=10), nullable=True),
    sa.Column('unix_epoch', sa.String(length=20), nullable=True),
    sa.Column('spd', sa.String(length=20), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
